trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'demo-docker-build'
    repository: 'ajim98/demo-container'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'